# Generated by Django 2.0.2 on 2018-04-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hifz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayat_number', models.IntegerField()),
                ('surah', models.IntegerField()),
                ('last_refreshed', models.DateField()),
            ],
        ),
    ]
